// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pablog.bookdb.domain;

import org.pablog.bookdb.domain.Book;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Book_Roo_Configurable {
    
    declare @type: Book: @Configurable;
    
}
